kind: pipeline
name: kernel_santoni

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Compile
    image: archlinux:latest
    commands:
      - pacman -Sy && pacman -S --needed --noconfirm base-devel bash bc zip unzip curl git wget zstd
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/zeta96/kernelci/master/L_drone_clang)"
    when:
      branch:
        - msm-3.18-googlexx
